# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
before:
  hooks:
    - go mod download
    - go install golang.org/x/tools/cmd/stringer@latest
    - go generate ./...
builds:
  - flags:
      - -trimpath
    ldflags:
      - "-s -w -X {{.ModulePath}}/cmd.version={{ .Version }} -X {{.ModulePath}}/cmd.revision={{ .ShortCommit}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: arm
      
archives:
  - format: tgz
    name_template: >-
      {{ .ProjectName }}-
      {{ .Version }}-
      {{ .Os }}-
      {{ if eq .Arch "amd64" }}x86_64
      {{ else }}{{ .Arch}}
      {{ if .Arm }}_v{{ .Arm }}{{ end }}
    files:
      - info:
          mtime: "{{ .CommitDate }}"
      - src: CHANGELOG*
        dst: docs
      - src: README*
        dst: docs
      - src: LICENSE*
        dst: docs
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-dev"
changelog:
  disable: true
release:
  github:
    owner: asphaltbuffet
    name: newed
  prerelease: auto
announce:
  skip: 'true'