# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
before:
  hooks:
    - go mod download
    - go install golang.org/x/tools/cmd/stringer@latest
    - go generate ./...
builds:
  - ldflags:
      - -s -w -X {{.ModulePath}}/cmd.Version={{.Summary}} -X {{.ModulePath}}/cmd.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      
archives:
  - format: tgz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86-64
      {{- else if eq .Arch "arm" }}arm-v6
      {{- else if eq .Arch "arm64" }}arm-v8
      {{- else }}{{ .Arch}}{{ end }}
    files:
      - info:
          mtime: "{{ .CommitDate }}"
      - src: CHANGELOG*
        dst: docs
      - src: README*
        dst: docs
      - src: LICENSE*
        dst: docs
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next-{{ .Now.Format \"0102-150405\" }}"
changelog:
  disable: true
release:
  prerelease: auto
announce:
  skip: 'true'