name: Linting
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write
  pull-requests: read
  packages: read
  statuses: write

jobs:
  lint:
    uses: asphaltbuffet/.github/.github/workflows/lint.yml@main